#categories - ready
Category.create(name: 'Biografia', booksCount: 0);
Category.create(name: 'Fantastyka', booksCount: 0);
Category.create(name: 'Historyczna', booksCount: 0);
Category.create(name: 'Klasyka', booksCount: 0);
Category.create(name: 'Literatura Młodzieżowa', booksCount: 0);
Category.create(name: 'Literatura Faktu', booksCount: 0);
Category.create(name: 'Literatura Współczesna', booksCount: 0);
Category.create(name: 'Przygodowa', booksCount: 0);
Category.create(name: 'Romans', booksCount: 0);
Category.create(name: 'Kryminał', booksCount: 0);
Category.create(name: 'Dramat', booksCount: 0);
Category.create(name: 'Komedia', booksCount: 0);
Category.create(name: 'Astronomia', booksCount: 0);
Category.create(name: 'Finanse', booksCount: 0);
Category.create(name: 'Encyklopedie', booksCount: 0);
Category.create(name: 'Filozofia', booksCount: 0);
Category.create(name: 'Fauna i Flora', booksCount: 0);
Category.create(name: 'Podróżnicze', booksCount: 0);
Category.create(name: 'Informatyka', booksCount: 0);
Category.create(name: 'Matematyka', booksCount: 0);
Category.create(name: 'Popularnonałkowe', booksCount: 0);
Category.create(name: 'Poradniki', booksCount: 0);